services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=UTC
      - TZ=UTC
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

  short-video-maker:
    image: gyoridavid/short-video-maker:latest-tiny
    container_name: short-video-maker
    ports:
      - "3123:3123"
    environment:
      - LOG_LEVEL=debug
      - PEXELS_API_KEY=yK8enpySKWtrlsCCs3ENQcPzCaJcCXAXZEq63vrqhBzPe1N2JdKbpX5K
      - CORS_ORIGIN=http://localhost:3000  
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 8G 
    restart: unless-stopped
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always


volumes:
  n8n_data:
  ollama_data: